version: '3'

services:
  # Database
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
      - 443:443
    restart: always
    volumes:
      - './app/wordpress/wp-admin:/var/www/html/wp-admin'
      - './app/wordpress/wp-includes:/var/www/html/wp-includes'
      - 'wordpress-themes:/var/www/html/wp-content/themes/:nocopy'
      - 'wordpress-plugins:/var/www/html/wp-content/plugins/:nocopy'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
  wordpress-themes:
    external: true
  wordpress-plugins:
    external: true